"""AMDR reference-aligned research components."""

from .data import (
    CANONICAL_SLOT_ORDER,
    PEAK_RELATIVE_AMPLITUDE_TRANSFORM_ID,
    PEAK_RELATIVE_POWER_TRANSFORM_ID,
    RANDOMIZED_SLOT_ORDER,
    TwoViewPair,
    assign_odd_angle_folds,
    build_fold_pairs,
    materialize_pair_views,
    peak_relative_amplitude_from_power_db,
    peak_relative_power_from_db,
)
from .model import (
    ALLOW_SAME_BASE_GRAPH,
    AMDR_ALGORITHM_VERSION,
    AMDRCheckpoint,
    AMDRFitResult,
    AMDRModelConfig,
    EXCLUDE_SAME_BASE_GRAPH,
    fit_amdr,
    knn_predict_and_score,
    load_amdr_checkpoint,
    prune_amdr_weight_rows,
    project_views,
    save_amdr_checkpoint,
)
from .reduction import (
    SHARED_TRAIN_BASE_PCA,
    SharedPCAModel,
    apply_shared_pca,
    fit_shared_pca,
)

__all__ = [
    "ALLOW_SAME_BASE_GRAPH",
    "AMDR_ALGORITHM_VERSION",
    "AMDRCheckpoint",
    "AMDRFitResult",
    "AMDRModelConfig",
    "CANONICAL_SLOT_ORDER",
    "EXCLUDE_SAME_BASE_GRAPH",
    "PEAK_RELATIVE_AMPLITUDE_TRANSFORM_ID",
    "PEAK_RELATIVE_POWER_TRANSFORM_ID",
    "RANDOMIZED_SLOT_ORDER",
    "SHARED_TRAIN_BASE_PCA",
    "SharedPCAModel",
    "TwoViewPair",
    "assign_odd_angle_folds",
    "apply_shared_pca",
    "build_fold_pairs",
    "fit_amdr",
    "fit_shared_pca",
    "knn_predict_and_score",
    "load_amdr_checkpoint",
    "materialize_pair_views",
    "peak_relative_amplitude_from_power_db",
    "peak_relative_power_from_db",
    "prune_amdr_weight_rows",
    "project_views",
    "save_amdr_checkpoint",
]
